-- VeloQuest verified archive + remote-media wave.
-- Every bicycle row has first-party model-year evidence and satisfies model_year >= 2020.
-- Images remain remote: only HTTPS source URLs are stored, never image binaries.

insert into public.bike_catalog_models
  (id, brand, model, model_year, category, market, specs, manufacturer_url, evidence_checked_at)
values
  ('salsa-cutthroat-c-grx-610-1x-2025-us', 'Salsa', 'Cutthroat C GRX 610 1x', 2025, 'gravel_bikepacking', 'US',
   '{"frame_material":"carbon","wheel_size":"29","drivetrain_brand":"Shimano","drivetrain":"GRX RX822 / RX610, 12-speed","brake_type":"hydraulic_disc","brakes":"Shimano GRX RX400","bottom_bracket":"Press Fit BB92 41x92 mm","udh_compatible":true,"model_year_evidence":"official Salsa archived product title and URL explicitly identify 2025"}'::jsonb,
   'https://www.salsacycles.com/products/2025-cutthroat-c-grx-610-1x', '2026-08-06'),
  ('salsa-cutthroat-c-force-x0-axs-2025-us', 'Salsa', 'Cutthroat C Force X0 AXS Transmission', 2025, 'gravel_bikepacking', 'US',
   '{"frame_material":"carbon","drivetrain_brand":"SRAM","model_year_evidence":"official Salsa archived product title and URL explicitly identify 2025"}'::jsonb,
   'https://www.salsacycles.com/products/2025-cutthroat-c-force-xo-axs-transmission', '2026-08-06'),
  ('salsa-beargrease-c-xt-2025-us', 'Salsa', 'Beargrease C XT', 2025, 'fat_bike', 'US',
   '{"frame_material":"carbon","drivetrain_brand":"Shimano","model_year_evidence":"official Salsa archived product title and URL explicitly identify 2025"}'::jsonb,
   'https://www.salsacycles.com/products/2025-beargrease-c-xt', '2026-08-06'),
  ('salsa-warbird-c-grx-600-1x-2024-us', 'Salsa', 'Warbird C GRX 600 1x', 2024, 'gravel_race', 'US',
   '{"frame_material":"carbon","drivetrain_brand":"Shimano","model_year_evidence":"official Salsa archived product title and URL explicitly identify 2024"}'::jsonb,
   'https://www.salsacycles.com/products/2024-warbird-c-grx-600-1x', '2026-08-06'),
  ('salsa-warbird-c-frameset-2024-us', 'Salsa', 'Warbird C Frameset', 2024, 'gravel_race', 'US',
   '{"frame_material":"carbon","frameset":true,"model_year_evidence":"official Salsa archived product title and URL explicitly identify 2024"}'::jsonb,
   'https://www.salsacycles.com/products/2024-warbird-c-frameset', '2026-08-06'),
  ('salsa-heyday-advent-2024-us', 'Salsa', 'Heyday! Advent', 2024, 'fat_bike', 'US',
   '{"frame_material":"aluminium","model_year_evidence":"official Salsa archived product title and URL explicitly identify 2024"}'::jsonb,
   'https://www.salsacycles.com/products/2024-heyday-advent', '2026-08-06'),
  ('salsa-cutthroat-c-rival-gx-axs-2024-us', 'Salsa', 'Cutthroat C Rival GX AXS Transmission', 2024, 'gravel_bikepacking', 'US',
   '{"frame_material":"carbon","drivetrain_brand":"SRAM","model_year_evidence":"official Salsa archived product title and URL explicitly identify 2024"}'::jsonb,
   'https://www.salsacycles.com/products/2024-cutthroat-c-rival-gx-axs-transmission', '2026-08-06'),
  ('salsa-cutthroat-c-frameset-2024-us', 'Salsa', 'Cutthroat C Frameset', 2024, 'gravel_bikepacking', 'US',
   '{"frame_material":"carbon","frameset":true,"model_year_evidence":"official Salsa archived product title and URL explicitly identify 2024"}'::jsonb,
   'https://www.salsacycles.com/products/2024-cutthroat-c-frameset', '2026-08-06'),
  ('salsa-beargrease-c-xt-2024-us', 'Salsa', 'Beargrease C XT', 2024, 'fat_bike', 'US',
   '{"frame_material":"carbon","drivetrain_brand":"Shimano","model_year_evidence":"official Salsa archived product title and URL explicitly identify 2024"}'::jsonb,
   'https://www.salsacycles.com/products/2024-beargrease-c-xt', '2026-08-06'),
  ('salsa-beargrease-c-cues-2024-us', 'Salsa', 'Beargrease C CUES', 2024, 'fat_bike', 'US',
   '{"frame_material":"carbon","drivetrain_brand":"Shimano","model_year_evidence":"official Salsa archived product title and URL explicitly identify 2024"}'::jsonb,
   'https://www.salsacycles.com/products/2024-beargrease-c-cues', '2026-08-06'),

  ('marin-rift-zone-el-xr-2025-int', 'Marin', 'Rift Zone EL XR', 2025, 'emtb_light_full_suspension', 'global',
   '{"frame_material":"Series 4 aluminium","wheel_size":"29","front_travel_mm":150,"rear_travel_mm":140,"motor":"Bosch Performance Line SX","motor_peak_power_w":600,"motor_torque_nm":55,"battery_wh":400,"suspension_brand":"Fox","fork":"Fox 36 Performance Elite","rear_shock":"Fox Float X Performance Elite","drivetrain_brand":"SRAM","drivetrain":"GX AXS T-Type","brake_type":"hydraulic_disc","brakes":"Magura MT7 4-piston","rear_spacing":"148x12","model_year_evidence":"official Marin product URL and page explicitly identify 2025"}'::jsonb,
   'https://marinbikes.com/products/2025-rift-zone-el-xr-int', '2026-08-06'),
  ('marin-rift-zone-el2-2025-int', 'Marin', 'Rift Zone EL2', 2025, 'emtb_light_full_suspension', 'global',
   '{"frame_material":"Series 4 aluminium","wheel_size":"29","front_travel_mm":150,"rear_travel_mm":140,"motor":"Bosch Performance Line SX","motor_peak_power_w":600,"motor_torque_nm":55,"battery_wh":400,"suspension_brand":"Fox","fork":"Fox 36 Performance","rear_shock":"Fox Float X Performance","drivetrain_brand":"SRAM","drivetrain":"Eagle 90 / GX T-Type","brake_type":"hydraulic_disc","brakes":"SRAM Code Bronze 4-piston","model_year_evidence":"official Marin product URL and page explicitly identify 2025"}'::jsonb,
   'https://marinbikes.com/products/2025-rift-zone-el2-int', '2026-08-06'),
  ('marin-lombard-e2-2025-us', 'Marin', 'Lombard E2', 2025, 'electric_allroad', 'US',
   '{"model_year_evidence":"official Marin product URL explicitly identifies 2025"}'::jsonb,
   'https://marinbikes.com/products/2025-1-lombard-e2', '2026-08-06'),
  ('marin-rift-zone-xr-2025-us', 'Marin', 'Rift Zone XR', 2025, 'trail_full_suspension', 'US',
   '{"model_year_evidence":"official Marin product URL explicitly identifies 2025"}'::jsonb,
   'https://marinbikes.com/products/2025-rift-zone-xr', '2026-08-06'),
  ('marin-team-marin-2-2024-us', 'Marin', 'Team Marin 2', 2024, 'xc_hardtail', 'US',
   '{"model_year_evidence":"official Marin product URL explicitly identifies 2024"}'::jsonb,
   'https://marinbikes.com/products/2024-team-marin-2', '2026-08-06'),
  ('marin-gestalt-xr-2024-us', 'Marin', 'Gestalt XR', 2024, 'gravel', 'US',
   '{"model_year_evidence":"official Marin product URL explicitly identifies 2024"}'::jsonb,
   'https://marinbikes.com/products/2024-gestalt-xr-copy', '2026-08-06'),
  ('marin-rift-zone-jr-26-2025-us', 'Marin', 'Rift Zone JR 26', 2025, 'youth_full_suspension', 'US',
   '{"wheel_size":"26","model_year_evidence":"official Marin product URL explicitly identifies 2025"}'::jsonb,
   'https://marinbikes.com/products/2025-1-rift-zone-jr-26', '2026-08-06'),
  ('marin-dsx-fs-2026-us', 'Marin', 'DSX FS', 2026, 'gravel_suspension', 'US',
   '{"model_year_evidence":"official Marin product URL explicitly identifies 2026"}'::jsonb,
   'https://marinbikes.com/products/2026-dsx-fs', '2026-08-06'),
  ('marin-fairfax-e-st-2025-int', 'Marin', 'Fairfax E ST', 2025, 'electric_fitness', 'global',
   '{"model_year_evidence":"official Marin product URL explicitly identifies 2025"}'::jsonb,
   'https://marinbikes.com/products/2025-fairfax-e-st-int', '2026-08-06'),
  ('marin-team-marin-1-2024-us', 'Marin', 'Team Marin 1', 2024, 'xc_hardtail', 'US',
   '{"model_year_evidence":"official Marin product URL explicitly identifies 2024"}'::jsonb,
   'https://marinbikes.com/products/2024-team-marin-1', '2026-08-06'),
  ('marin-dsx-2-2025-us', 'Marin', 'DSX 2', 2025, 'gravel', 'US',
   '{"model_year_evidence":"official Marin product URL explicitly identifies 2025"}'::jsonb,
   'https://marinbikes.com/products/2025-1-dsx-2', '2026-08-06'),
  ('marin-gestalt-1-2023-us', 'Marin', 'Gestalt 1', 2023, 'gravel', 'US',
   '{"model_year_evidence":"official Marin product URL explicitly identifies 2023"}'::jsonb,
   'https://marinbikes.com/products/2023-gestalt-1', '2026-08-06'),
  ('marin-dsx-1-2025-us', 'Marin', 'DSX 1', 2025, 'gravel', 'US',
   '{"model_year_evidence":"official Marin product URL explicitly identifies 2025"}'::jsonb,
   'https://marinbikes.com/products/2025-1-dsx-1', '2026-08-06'),

  ('norco-optic-a1-gen3-2025-ca', 'Norco', 'Optic A1 Gen 3', 2025, 'trail_full_suspension', 'CA',
   '{"frame_material":"aluminium","wheel_size":"29","front_travel_mm":140,"rear_travel_mm":125,"model_year_evidence":"official Norco MY25 Optic product page explicitly identifies the 2025 Optic"}'::jsonb,
   'https://www.norco.com/bikes/mountain/trail/optic/25-optic-a1/', '2026-08-06'),
  ('norco-optic-a2-gen3-2025-ca', 'Norco', 'Optic A2 Gen 3', 2025, 'trail_full_suspension', 'CA',
   '{"frame_material":"aluminium","wheel_size":"29","front_travel_mm":140,"rear_travel_mm":125,"model_year_evidence":"official Norco MY25 Optic product page explicitly identifies the 2025 Optic"}'::jsonb,
   'https://www.norco.com/bikes/mountain/trail/optic/25-optic-a2/', '2026-08-06'),
  ('norco-optic-c2-gen3-2025-global', 'Norco', 'Optic C2 Gen 3', 2025, 'trail_full_suspension', 'global',
   '{"frame_material":"carbon","wheel_size":"29","front_travel_mm":140,"rear_travel_mm":125,"model_year_evidence":"official Norco MY25 Optic product page explicitly identifies the 2025 Optic"}'::jsonb,
   'https://www.norco.com/bikes/mountain/trail/optic/25-optic-C2/', '2026-08-06'),

  ('yeti-sb140-29-2025-us', 'Yeti', 'SB140 29', 2025, 'trail_full_suspension', 'US',
   '{"frame_material":"carbon","wheel_size":"29","rear_travel_mm":140,"family_level":true,"model_year_evidence":"official Yeti archive explicitly lists SB140 29 for 2023-2025"}'::jsonb,
   'https://yeticycles.com/en-us/archive', '2026-08-06'),
  ('yeti-sb120-2025-us', 'Yeti', 'SB120', 2025, 'xc_trail_full_suspension', 'US',
   '{"frame_material":"carbon","wheel_size":"29","rear_travel_mm":120,"family_level":true,"model_year_evidence":"official Yeti archive explicitly lists SB120 for 2023-2025"}'::jsonb,
   'https://yeticycles.com/en-us/archive', '2026-08-06'),
  ('yeti-sb160-2025-us', 'Yeti', 'SB160', 2025, 'enduro_full_suspension', 'US',
   '{"frame_material":"carbon","wheel_size":"29","rear_travel_mm":160,"family_level":true,"model_year_evidence":"official Yeti archive explicitly lists SB160 for 2023-2025"}'::jsonb,
   'https://yeticycles.com/en-us/archive', '2026-08-06'),
  ('yeti-sb165-2025-us', 'Yeti', 'SB165', 2025, 'enduro_full_suspension', 'US',
   '{"frame_material":"carbon","family_level":true,"model_year_evidence":"official Yeti archive explicitly lists SB165 for 2023-2026"}'::jsonb,
   'https://yeticycles.com/en-us/archive', '2026-08-06'),

  ('pivot-les-2025-global', 'Pivot', 'LES', 2025, 'xc_hardtail', 'global',
   '{"family_level":true,"model_year_evidence":"official Pivot Bike Archive lists LES through model year 2025"}'::jsonb,
   'https://www.pivotcycles.com/en/bike-archive', '2026-08-06'),
  ('pivot-mach-4-2025-global', 'Pivot', 'Mach 4', 2025, 'xc_full_suspension', 'global',
   '{"family_level":true,"model_year_evidence":"official Pivot Bike Archive lists Mach 4 through model year 2025"}'::jsonb,
   'https://www.pivotcycles.com/en/bike-archive', '2026-08-06'),
  ('pivot-mach-6-2025-global', 'Pivot', 'Mach 6', 2025, 'enduro_full_suspension', 'global',
   '{"family_level":true,"model_year_evidence":"official Pivot Bike Archive lists Mach 6 through model year 2025"}'::jsonb,
   'https://www.pivotcycles.com/en/bike-archive', '2026-08-06'),
  ('pivot-shuttle-am-2025-global', 'Pivot', 'Shuttle AM', 2025, 'emtb_full_suspension', 'global',
   '{"family_level":true,"model_year_evidence":"official Pivot Bike Archive lists Shuttle AM through model year 2025"}'::jsonb,
   'https://www.pivotcycles.com/en/bike-archive', '2026-08-06'),
  ('pivot-shuttle-lt-2025-global', 'Pivot', 'Shuttle LT', 2025, 'emtb_full_suspension', 'global',
   '{"family_level":true,"model_year_evidence":"official Pivot Bike Archive lists Shuttle LT through model year 2025"}'::jsonb,
   'https://www.pivotcycles.com/en/bike-archive', '2026-08-06'),

  ('rocky-mountain-element-carbon-99-2025-int', 'Rocky Mountain', 'Element Carbon 99', 2025, 'xc_full_suspension', 'global',
   '{"frame_material":"carbon","wheel_size":"29 / 27.5 XS","rear_travel_mm":120,"fork":"RockShox SID Ultimate Flight Attendant 120mm","drivetrain_brand":"SRAM","drivetrain":"XX Eagle Transmission Wireless","brake_type":"hydraulic_disc","model_year_evidence":"official Rocky Mountain 2025 collection and product URL suffix -25"}'::jsonb,
   'https://bikes.com/en-intl/products/element-c99-25', '2026-08-06'),
  ('rocky-mountain-element-carbon-70-2025-int', 'Rocky Mountain', 'Element Carbon 70', 2025, 'xc_full_suspension', 'global',
   '{"frame_material":"carbon","rear_travel_mm":120,"fork":"Fox 34 Float Performance Elite","drivetrain_brand":"SRAM","drivetrain":"GX Eagle Transmission Wireless","model_year_evidence":"official Rocky Mountain 2025 collection and product URL suffix -25"}'::jsonb,
   'https://bikes.com/en-intl/products/element-c70-25', '2026-08-06'),
  ('rocky-mountain-altitude-alloy-70-coil-2025-int', 'Rocky Mountain', 'Altitude Alloy 70 Coil', 2025, 'enduro_full_suspension', 'global',
   '{"frame_material":"aluminium","suspension_brand":"Fox","fork":"Fox 38 Float EVOL GRIP2 Factory","rear_shock":"Fox DHX Coil Factory","drivetrain_brand":"Shimano","brakes":"Shimano XT Trail 4 Piston","model_year_evidence":"official Rocky Mountain 2025 collection and product URL suffix -25"}'::jsonb,
   'https://bikes.com/en-intl/products/altitude-a70-coil-25', '2026-08-06')
on conflict (id) do update set
  brand = excluded.brand,
  model = excluded.model,
  model_year = excluded.model_year,
  category = excluded.category,
  market = excluded.market,
  specs = excluded.specs,
  manufacturer_url = excluded.manufacturer_url,
  evidence_checked_at = excluded.evidence_checked_at,
  enabled = true;

insert into public.bike_catalog_images
  (bike_id, image_url, source_type, source_name, source_page_url, priority, checked_at)
values
  ('salsa-cutthroat-c-grx-610-1x-2025-us',
   'https://www.salsacycles.com/cdn/shop/files/salsa-cutthroat-c-grx-610-bike-dark-pine-BK00428-1920x1080-uc-1.png?v=1739311277&width=1946',
   'manufacturer', 'Salsa', 'https://www.salsacycles.com/products/2025-cutthroat-c-grx-610-1x', 10, '2026-08-06'),
  ('marin-rift-zone-el-xr-2025-int',
   'https://marinbikes.com/cdn/shop/files/2025_MARIN_BIKES_RIFT_ZONE_EL_XR_TAN_BROWN_SIDE.png?v=1753785495&width=1000',
   'manufacturer', 'Marin', 'https://marinbikes.com/products/2025-rift-zone-el-xr-int', 10, '2026-08-06'),
  ('marin-rift-zone-el2-2025-int',
   'https://marinbikes.com/cdn/shop/files/2025_MARIN_BIKES_RIFT_ZONE_EL_2_SILVER_SIDE.png?v=1771956712&width=1000',
   'manufacturer', 'Marin', 'https://marinbikes.com/products/2025-rift-zone-el2-int', 10, '2026-08-06'),
  ('rocky-mountain-element-carbon-99-2025-int',
   'https://bikes.com/cdn/shop/files/Web_MY25_Element_C99_C3_29_Profile.jpg?v=1743703741&width=2500',
   'manufacturer', 'Rocky Mountain', 'https://bikes.com/en-intl/products/element-c99-25', 10, '2026-08-06')
on conflict (bike_id, image_url) do update set
  source_type = excluded.source_type,
  source_name = excluded.source_name,
  source_page_url = excluded.source_page_url,
  priority = excluded.priority,
  checked_at = excluded.checked_at,
  enabled = true;
