-- VeloQuest verified brand-expansion wave.
-- All rows require an explicit first-party model-year 2020+ signal.

insert into public.bike_catalog_models
  (id, brand, model, model_year, category, market, specs, manufacturer_url, evidence_checked_at)
values
  ('argon18-anti-matter-frameset-2026-us', 'Argon 18', 'Anti Matter Frameset', 2026, 'gravel_race', 'US',
   '{"frame_material":"carbon","model_year_evidence":"official lineup explicitly labels Anti Matter frameset (2026)","model_year_evidence_url":"https://www.argon18.com/en-us/bikes"}'::jsonb,
   'https://www.argon18.com/en-us/bikes', '2026-08-06'),

  ('bh-igravelx-2026-global', 'BH', 'iGRAVELX', 2026, 'electric_gravel', 'global',
   '{"model_year_evidence":"official BH iGRAVELX user manual identifies 2026","model_year_evidence_url":"https://www.bhbikes.com/download/bancorecursos/manuales/ENG/2026/2026_iGRAVELX_ENG_USER_MANUAL.pdf"}'::jsonb,
   'https://www.bhbikes.com/download/bancorecursos/manuales/ENG/2026/2026_iGRAVELX_ENG_USER_MANUAL.pdf', '2026-08-06'),

  ('ktm-macina-prowler-exonic-2026-global', 'KTM', 'Macina Prowler Exonic', 2026, 'electric_enduro', 'global',
   '{"model_year_evidence":"official KTM MY2026 page names model for 2026","motor":"Bosch Performance Line CX-R"}'::jsonb,
   'https://www.ktm-bikes.at/my2025/my2026', '2026-08-06'),
  ('ktm-macina-prowler-prestige-2026-global', 'KTM', 'Macina Prowler Prestige', 2026, 'electric_enduro', 'global',
   '{"model_year_evidence":"official KTM MY2026 page names model for 2026"}'::jsonb,
   'https://www.ktm-bikes.at/my2025/my2026', '2026-08-06'),
  ('ktm-macina-kapoho-exonic-2026-global', 'KTM', 'Macina Kapoho Exonic', 2026, 'electric_all_mountain', 'global',
   '{"model_year_evidence":"official KTM MY2026 page names model for 2026","motor":"Bosch Performance Line CX-R"}'::jsonb,
   'https://www.ktm-bikes.at/my2025/my2026', '2026-08-06'),
  ('ktm-macina-kapoho-pro-ltd-2026-global', 'KTM', 'Macina Kapoho Pro LTD', 2026, 'electric_all_mountain', 'global',
   '{"model_year_evidence":"official KTM MY2026 page lists new Kapoho model","frame_material":"carbon main triangle / aluminium rear triangle"}'::jsonb,
   'https://www.ktm-bikes.at/my2025/my2026', '2026-08-06'),
  ('ktm-macina-kapoho-comp-ltd-2026-global', 'KTM', 'Macina Kapoho Comp LTD', 2026, 'electric_all_mountain', 'global',
   '{"model_year_evidence":"official KTM MY2026 page lists new Kapoho model","frame_material":"carbon main triangle / aluminium rear triangle"}'::jsonb,
   'https://www.ktm-bikes.at/my2025/my2026', '2026-08-06'),
  ('ktm-macina-tour-px-810-2026-global', 'KTM', 'Macina Tour PX 810', 2026, 'electric_trekking', 'global',
   '{"motor":"Bosch Performance Line PX","motor_torque_nm":90,"battery_wh":800,"model_year_evidence":"official KTM MY2026 page names model"}'::jsonb,
   'https://www.ktm-bikes.at/my2025/my2026', '2026-08-06'),
  ('ktm-macina-tour-px-610-2026-global', 'KTM', 'Macina Tour PX 610', 2026, 'electric_trekking', 'global',
   '{"motor":"Bosch Performance Line PX","motor_torque_nm":90,"battery_wh":600,"model_year_evidence":"official KTM MY2026 page names model"}'::jsonb,
   'https://www.ktm-bikes.at/my2025/my2026', '2026-08-06'),
  ('ktm-macina-fold-2026-global', 'KTM', 'Macina Fold', 2026, 'electric_folding', 'global',
   '{"motor":"Bosch Performance Line PX","battery_wh":500,"drivetrain":"Nexus belt 1x8","model_year_evidence":"official KTM MY2026 page names model"}'::jsonb,
   'https://www.ktm-bikes.at/my2025/my2026', '2026-08-06'),
  ('ktm-gravelator-exonic-2026-global', 'KTM', 'Gravelator Exonic', 2026, 'gravel', 'global',
   '{"model_year_evidence":"official product page explicitly states model year 2026","drivetrain":"SRAM RED XPLR AXS 1x13"}'::jsonb,
   'https://www.ktm-bikes.at/bikes/detail/mx1260460115-gravelator-exonic-m-55-mx1260460115-gravelator-exonic-spotted-white-ornge-blk-grey-1x13-sram-red-xplr-axs-2026', '2026-08-06'),

  ('stevens-camino-rs-2026-de', 'STEVENS', 'Camino RS', 2026, 'gravel_race', 'DE',
   '{"max_tire_clearance_mm":45,"model_year_evidence":"official STEVENS Collection 2026"}'::jsonb,
   'https://www.stevensbikes.de/en/de/highlights-collection-2026/', '2026-08-06'),
  ('stevens-camino-pro-di2-2026-de', 'STEVENS', 'Camino Pro Di2', 2026, 'gravel', 'DE',
   '{"frame_material":"carbon","max_tire_clearance_mm":45,"drivetrain":"Shimano GRX 825 Di2 2x12","model_year_evidence":"official STEVENS Collection 2026"}'::jsonb,
   'https://www.stevensbikes.de/en/de/gravel/gravel/camino-pro-di2/', '2026-08-06'),
  ('stevens-gavere-pro-feq-2026-de', 'STEVENS', 'Gavere Pro FEQ', 2026, 'gravel_commuter', 'DE',
   '{"frame_material":"aluminium","drivetrain":"SRAM Apex AXS 1x12","wheels":"DT Swiss G 1800","model_year_evidence":"official product page Highlights 2026"}'::jsonb,
   'https://www.stevensbikes.de/en/de/gravel/gravel/gavere-pro-feq/', '2026-08-06'),
  ('stevens-colorado-401-2026-de', 'STEVENS', 'Colorado 401', 2026, 'xc_hardtail', 'DE',
   '{"frame_material":"aluminium","fork":"Fox 32 Float Rhythm","drivetrain":"Shimano Deore XT/SLX 1x12","model_year_evidence":"official product page Highlights 2026"}'::jsonb,
   'https://www.stevensbikes.de/en/de/mtb/colorado-401/', '2026-08-06'),
  ('stevens-caleta-7-2-lt-2026-de', 'STEVENS', 'Caleta 7.2 LT', 2026, 'urban_trekking', 'DE',
   '{"frame_material":"aluminium","drivetrain":"Shimano Alfine 11 belt","brake_type":"hydraulic_disc","model_year_evidence":"official product page Highlights 2026"}'::jsonb,
   'https://www.stevensbikes.de/en/de/allround/caleta-7.2-lt', '2026-08-06'),
  ('stevens-amant-5-2-forma-2026-de', 'STEVENS', 'Amant 5.2 Forma', 2026, 'urban', 'DE',
   '{"drivetrain":"Shimano Nexus 8","brake_type":"hydraulic_disc","model_year_evidence":"official product page Highlights 2026"}'::jsonb,
   'https://www.stevensbikes.de/en/de/urban/amant-5.2-forma', '2026-08-06'),

  ('riese-muller-delite5-2026-global', 'Riese & Müller', 'Delite5', 2026, 'electric_trekking_full_suspension', 'global',
   '{"drive_options":["Bosch Performance Line CX","Bosch Performance Line Speed","Pinion MGU"],"model_year_evidence":"official press release explicitly states 2026 model year"}'::jsonb,
   'https://www.r-m.de/en-en/press/press-releases/e-bike-updates-at-riese-muller-delite5-superdelite5-and-swing5/', '2026-08-06'),
  ('riese-muller-superdelite5-2026-global', 'Riese & Müller', 'Superdelite5', 2026, 'electric_trekking_full_suspension', 'global',
   '{"battery_capacity_wh_max":1200,"model_year_evidence":"official press release explicitly states 2026 model year"}'::jsonb,
   'https://www.r-m.de/en-en/press/press-releases/e-bike-updates-at-riese-muller-delite5-superdelite5-and-swing5/', '2026-08-06'),
  ('riese-muller-swing5-2026-global', 'Riese & Müller', 'Swing5', 2026, 'electric_city', 'global',
   '{"motor":"Bosch Performance Line","model_year_evidence":"official press release explicitly states 2026 model year"}'::jsonb,
   'https://www.r-m.de/en-en/press/press-releases/e-bike-updates-at-riese-muller-delite5-superdelite5-and-swing5/', '2026-08-06'),

  ('gazelle-ultimate-c380-plus-2026-us', 'Gazelle', 'Ultimate C380+', 2026, 'electric_city', 'US',
   '{"motor":"Bosch Performance Line Sport","motor_torque_nm":90,"battery_wh":540,"drivetrain":"Enviolo stepless","assist_speed_mph":28,"model_year_evidence":"official Gazelle Summer Class of 2026"}'::jsonb,
   'https://www.gazellebikes.com/en-us/latest-models', '2026-08-06')
on conflict (id) do update set
  brand = excluded.brand,
  model = excluded.model,
  model_year = excluded.model_year,
  category = excluded.category,
  market = excluded.market,
  specs = excluded.specs,
  manufacturer_url = excluded.manufacturer_url,
  evidence_checked_at = excluded.evidence_checked_at,
  enabled = true;
